services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    user: root
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "192.168.86.202:8081:8081"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./config.yml:/config.yml:ro
      - ./acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik
      - /var/log/traefik:/var/log/traefik
    security_opt:
      - apparmor:unconfined
    cap_add:
      - NET_ADMIN
    command:
      - "--log.level=INFO"
      - "--log.format=json"
      - "--accesslog=true"
      - "--accesslog.format=json"
      - "--accesslog.bufferingsize=100"
      - "--accesslog.fields.defaultmode=keep"
      - "--accesslog.fields.headers.defaultmode=drop"
      - "--accesslog.fields.headers.names.User-Agent=keep"
      - "--accesslog.fields.headers.names.Authorization=redact"
      - "--accesslog.fields.headers.names.Content-Type=keep"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    user: root
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail.yml:/etc/promtail/config.yml:ro
      - promtail-positions:/tmp
      - /var/log/traefik:/var/log/traefik:ro  # Add this to access Traefik logs
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped
    ports:
      - "9080:9080"
    environment:
      HOSTNAME: "192.168.86.202"
    stop_grace_period: 30s

volumes:
  promtail-positions:
